/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import model.Account;
import model.AccountDirectory;
import ui.AccountManager.AccountMngWorkAreaJpanel;
/**
 *
 * @author chw
 */
public class MainJFrame extends javax.swing.JFrame {

    private AccountDirectory accountDirectory;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        
        this.accountDirectory = new AccountDirectory();
        generateDemoDate(); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        topJpanel = new javax.swing.JPanel();
        btnAccountMng = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setSize(new java.awt.Dimension(80, 100));

        jSplitPane1.setDividerLocation(80);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setToolTipText("");

        btnAccountMng.setBackground(new java.awt.Color(153, 153, 255));
        btnAccountMng.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnAccountMng.setText("Person Profile");
        btnAccountMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountMngActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topJpanelLayout = new javax.swing.GroupLayout(topJpanel);
        topJpanel.setLayout(topJpanelLayout);
        topJpanelLayout.setHorizontalGroup(
            topJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAccountMng, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                .addContainerGap())
        );
        topJpanelLayout.setVerticalGroup(
            topJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJpanelLayout.createSequentialGroup()
                .addComponent(btnAccountMng, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(topJpanel);

        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSplitPane1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccountMngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountMngActionPerformed
        // TODO add your handling code here:
        AccountMngWorkAreaJpanel panel = new AccountMngWorkAreaJpanel(userProcessContainer,accountDirectory);
        userProcessContainer.add("AccountMngWorkAreaJpanel",panel);
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnAccountMngActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccountMng;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel topJpanel;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables

  private void generateDemoDate() {

    Account newAccount = accountDirectory.addAccount();
    newAccount.setFirstName("Jack");
    newAccount.setLastName("CHEN");
    newAccount.setSSN(01); 
    newAccount.setAge((short) 22);
    newAccount.setStreetAddress("02115");
    newAccount.setUnitNumber("2");
    newAccount.setCity("Boston");
    newAccount.setState("MA");
    newAccount.setZipCode(2115); 
    newAccount.setPhoneNumber(200100111L); 
    newAccount.setStreetAddress1("NEU");
    newAccount.setUnitNumber1("1");
    newAccount.setCity1("Boston");
    newAccount.setState1("MA");
    newAccount.setZipCode1(2115); 
    newAccount.setPhoneNumber1(0L); 

    Account anotherNewAccount = accountDirectory.addAccount();
    anotherNewAccount.setFirstName("Mike");
    anotherNewAccount.setLastName("Chen");
    anotherNewAccount.setSSN(0L); 
    anotherNewAccount.setAge((short) 20); 
    anotherNewAccount.setStreetAddress("02111");
    anotherNewAccount.setUnitNumber("1");
    anotherNewAccount.setCity("Boston");
    anotherNewAccount.setState("MA");
    anotherNewAccount.setZipCode(2115); 
    anotherNewAccount.setPhoneNumber(200L);
    anotherNewAccount.setStreetAddress1("NEU");
    anotherNewAccount.setUnitNumber1("2");
    anotherNewAccount.setCity1("Boston");
    anotherNewAccount.setState1("MA");
    anotherNewAccount.setZipCode1(2115); 
    anotherNewAccount.setPhoneNumber1(1L); 

    Account anotherNewAccount1 = accountDirectory.addAccount();
    anotherNewAccount1.setFirstName("Rose");
    anotherNewAccount1.setLastName("Jame");
    anotherNewAccount1.setSSN(1100221L);
    anotherNewAccount1.setAge((short) 21);
    anotherNewAccount1.setStreetAddress("02115");
    anotherNewAccount1.setUnitNumber("2");
    anotherNewAccount1.setCity("Boston");
    anotherNewAccount1.setState("MA");
    anotherNewAccount1.setZipCode(2115); 
    anotherNewAccount1.setPhoneNumber(2001L); 
    anotherNewAccount1.setStreetAddress1("NEU");
    anotherNewAccount1.setUnitNumber1("3");
    anotherNewAccount1.setCity1("Boston");
    anotherNewAccount1.setState1("MA");
    anotherNewAccount1.setZipCode1(2115); 
    anotherNewAccount1.setPhoneNumber1(2L); 

    Account anotherNewAccount2 = accountDirectory.addAccount();
    anotherNewAccount2.setFirstName("Jone");
    anotherNewAccount2.setLastName("Petter");
    anotherNewAccount2.setSSN(221133L); 
    anotherNewAccount2.setAge((short) 23); 
    anotherNewAccount2.setStreetAddress("02115");
    anotherNewAccount2.setUnitNumber("2");
    anotherNewAccount2.setCity("Boston");
    anotherNewAccount2.setState("MA");
    anotherNewAccount2.setZipCode(2110); 
    anotherNewAccount2.setPhoneNumber(200100100L); 
    anotherNewAccount2.setStreetAddress1("NEU");
    anotherNewAccount2.setUnitNumber1("2");
    anotherNewAccount2.setCity1("Boston");
    anotherNewAccount2.setState1("MA");
    anotherNewAccount2.setZipCode1(2122); 
    anotherNewAccount2.setPhoneNumber1(5L); 

    Account anotherNewAccount3 = accountDirectory.addAccount();
    anotherNewAccount3.setFirstName("OJ");
    anotherNewAccount3.setLastName("Yone");
    anotherNewAccount3.setSSN(222111L); // Set long value for SSN
    anotherNewAccount3.setAge((short) 28); // Cast to short
    anotherNewAccount3.setStreetAddress("02221");
    anotherNewAccount3.setUnitNumber("7");
    anotherNewAccount3.setCity("Boston");
    anotherNewAccount3.setState("MA");
    anotherNewAccount3.setZipCode(2115); // Parse as int
    anotherNewAccount3.setPhoneNumber(200112L); // Parse as long
    anotherNewAccount3.setStreetAddress1("NEU");
    anotherNewAccount3.setUnitNumber1("7");
    anotherNewAccount3.setCity1("Boston");
    anotherNewAccount3.setState1("MA");
    anotherNewAccount3.setZipCode1(2115); // Parse as int
    anotherNewAccount3.setPhoneNumber1(7L); // Replace "xxx7" with a default long value
}
}